# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Based on Pure preset

# Disable newlines between segments
add_newline = false

# Increase command duration to 2 seconds
command_timeout = 2000

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$character"""

[directory]
style = "blue"

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"

[git_branch]
format = "[$branch]($style)"
style = "green"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "cyan"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"
ahead = "↑"
behind = "↓"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"
